import Head from "next/head";

import { Box, Heading, Text } from "@chakra-ui/react";
import Link from "next/link";

export default function Module101() {

  return (
    <>
      <Head>
        <title>PPBL Módulo 101</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Heading>Módulo 101: Compila tu primer...</Heading>
        <Text>Este es un archivo en format .tsx</Text>
        <Text><Link href="./101/example">Haz click aquí</Link> para ver un archivo en formato .mdx.</Text>
      </Box>
    </>
  );
}
